### PR TITLE
Camera Refactor

### LINKED ISSUE #101: Camera Refactor
Slight refactor / extension of the camera class to promote better class design. This is to better support a good implementation of the input manager. Issue #83 will loosely depend on this.

- [x] Make members private.
- [x] Provide access methods.
- [x] Provide mutation methods.
- [x] Look into FoV vs Zoom (they may be synonymous in this case).

### PR DESCRIPTION
**Pull request by jdilanzo**
## What problem does this pull request address?
The camera class had pretty poor design in object-oriented terms. This slightly refactors / extends the camera class to promote better class design. This is to better support a good implementation of the input manager.

Closes #101.

## How does this pull request solve the problem?
The camera class member variables have been made private so that they cannot be accessed directly. Additional accessor and mutators have been provided as part of the public class API to interface with appropriate member variables. An additional mutator has been added to set the view matrix directly.

Some member variables are not able to be mutated directly because they are evaluated internally. These include:
- The front vector.
- The up vector.
- The right vector.
- The world up vector.

Some of the idea behind this is to promote good design for the input manager, and to allow camera functions to be registered with our scripting state. In that way, we can control the camera / player movement through scripts rather than through source code.

NB: The camera movement speed for the scene has been reduced, so it will appear **very** slow. This is just preparing the camera to be closer to the ground, and will ideally be alleviated after #102 is completed.

## What testing has been performed?
- [x] Builds and Runs.

TODO: Should add some unit tests.

## Changelist:
- Make member variables private.
- Add the `look_at_` member variable to represent the view matrix.
- Adjust and simplify class constructors. Only position is to be provided, and it is an optional argument.
- Adjust some class constants, increase max zoom to 80.
- Add accessor methods for class members: `GetFront`, `GetSensitivity`, `GetSpeed`, `GetPitch`, `GetPosition`, `GetPositionX`, `GetPositionY`, `GetPositionZ`, `GetRight`, `GetUp`, `GetWorldUp`, `GetZoom`, `GetYaw`.
- Add mutator methods for class members: `GetFront`, `GetSensitivity`, `GetSpeed`, `GetPitch`, `GetPosition`, `GetPositionX`, `GetPositionY`, `GetPositionZ`, `GetRight`, `GetUp`.
- Add mutator methods for class members: `SetSensitivity`, `SetSpeed`, `SetPitch`, `SetPosition` (vectors and floats), `SetPositionX`, `SetPositionY`, `SetPositionZ`, `SetViewMatrix`, `SetZoom`, `SetYaw`.
- Adjust camera values in entry point.
- Lower camera mouse sensitivity.
- Reduce camera movement speed.
- Reduce camera zoom (FoV).
- Straighten up splash screen cube.
- Adjust splash screen logic for new camera methods (sets view matrix directly).
- Add a restrict camera flag to allow for free camera or terrain locking. True by default. Press `R` to activate the free camera.
- Add 'sprint' control to speed up camera movement. Press and hold `Left Shift` to 'sprint'.

### CODE REVIEW

**Comment by jdilanzo** [comment]
It's 'super slow' because the evaluated terrain height ends up being quite high. It really just makes it appear super slow because we aren't all that close to the ground. In #102 I will adjust some evaluations to get the 'player' closer to the ground, so it won't appear quite as slow in that case. Obviously will adjust accordingly if it is too slow after that.

The slower movement speed and (eventual) shorter zoom (FoV) means that the world effectively appears larger, which gives us a better sense of scale.

**Comment by Idraliski** [comment]
@jdilanzo I see, you're attempting to make the landscape bigger than what it is, as it isn't really a concern with this particular PR. 
I'd imagine they'd be addressed when you've played around more with FOV and the terrain height calcs.

But note that I do seem to be able to get underneath the terrain at certain low points, like seen below
image

**Comment by jdilanzo** [comment]
@Idraliski it's a feature bro dw about it

**Comment by jdilanzo** [comment]
@Idraliski in seriousness, there will be issues like this present for the moment that I will address in #102. They are known to me. Figured it was best to keep this one limited to *just* the camera class (and associated inputs).

**Comment by Idraliski** [comment]
@jdilanzo yeah I figured as much. Still happy with the PR

**Review by Minywire — APPROVED** [review]

**Pull request merged**
