### PR TITLE
Terrain Refactor

### LINKED ISSUE #102: Terrain Refactor
Adjust certain algorithms in the terrain class to promote better accuracy in calculations, and ideally to support textures.

- [x] Adjust accuracy and scaling of `GetHeight` method.
- [x] Add basic support for textures.

### PR DESCRIPTION
**Pull request by jdilanzo**
## What problem does this pull request address?
The accuracy and scaling of the `GetHeight` method was erroneous, and additionally there were some slight errors in the calculations. The terrain also did not support textures of any kind. This attempts to address both.

Closes #102.

## How does this pull request solve the problem?
The `GetHeight` method has been adjusted so that errors are no longer present and so that it is not applying a scale and shift factor to the evaluated height upon return. This results in more consistent terrain collision that does not appear too high above the actual terrain height and does not fall through the terrain. This will now return the exact height value at the given *x* and *z* position, so an offset will be required to stay above the terrain. Currently, this offset is handled in `EntryPoint.cpp` and is set to 1.5.

Texture support has been added for the terrain mesh. This is a simple supporting addition, and currently does not support multiple textures or multitexturing. The single texture is applied to the whole terrain with scale and shift factors taken into account (though not sure if we should).

The demo scene uses a different heightmap to demonstrate these differences. As such, trees and houses appear far off since the scaling has been reduced. This can always be swapped out. The camera zoom has been adjusted to make the 'player' seem closer to the terrain, and movement speed has been adjusted to be more realistic.

Shaders have been adjusted to account for terrain textures, and have the added result of inducing a fake lighting effect on the terrain that lightens high points and darkens low points. Press `R` to unrestrict the camera and fly around to see for yourself.

Additionally, added a grayscale toggle. Toggle grayscale terrain using `G`.

## What testing has been performed?
- [x] Builds and Runs

TODO: Should add some unit tests.

## Changelist:
- Adjusted `GetHeight` method so that the returning height value is no longer affected implicitly by scale and shift factors.
- Fixed erroneous co-ordinate passing in the `GetHeight` method.
- Added the `GetMaxHeight` and `GetMinHeight` methods to the terrain class.
- Added a texture path argument to the terrain class constructor. This is the texture that will be used for the terrain.
- Removed terrain class destructor. Memory freeing occurs more immediately.
- Moved `Barycentric` function to outside of terrain class.
- Adjusted `EntryPoint.cpp` to demonstrate new changes.
- Added additional heightmaps.
- Added terrain textures.
- Swapped scene heightmap (for now). It just has nicer peaks and troughs.
- Added grayscale toggle: Press `G`.
- Adjusted shaders to support terrain textures.
- Added fake lighting effect via terrain shaders.

image

### CODE REVIEW

**Review by The-Spaghetti-Is-Ready — APPROVED** [review]
Good stuff. Lots of mess in entrypoint with the hardcoded textures but ultimately this is my problem as I'll be refactoring it all so that it's stored in the scene/resource manager.

**Comment by jdilanzo** [comment]
Yeah `EntryPoint.cpp` is messy. Ideally we will begin to rip things out once we get started on these managers.

**Review by Minywire — APPROVED** [review]
Apart from the things that Marco's already mentioned, this looks great!

**Comment by jdilanzo** [comment]
Will address using `Image` class and texture co-ordinate scaling as part of #83.

**Pull request merged**
