### PR TITLE
Window System

### LINKED ISSUE #110: Window System
Create a windowing context abstraction to wrap the GLFW windowing system and allow for flexible and controlled window creation. This will support a good input manager design for #83.

- [x] Window Creation
- [x] Window Removal
- [x] Window Closing
- [x] Window Sizing
- [x] Polling
- [x] Buffer Swapping
- [x] Fullscreen Support

### PR DESCRIPTION
**Pull request by jdilanzo**
## What problem does this pull request address?
We require a windowing interface to satisfy a core requirement and to support good input manager design and implementation.

Closes #110. Addresses part of #83.

## How does this pull request solve the problem?
This change provides a window interface that effectively wraps the GLFW windowing system. The `Window` class provides the necessary public interface to create, modify, and remove a GLFW window that we can use to display our rendered scene.

The class manages a window context and allows for operations on that context. The window interface is technically flexible and can support different GLFW window modes and cursor modes.

## What testing has been performed?
- [x] Builds and Runs.

TODO: Probably add some unit tests.

## Changelist:
- Add the `Window` class.
- Add `WindowContext` that typedefs `GLFWwindow*`.
- Add `WindowMonitor` that typedefs `GLFWmonitor*`.
- Add `WindowVideoMode` that typedefs `const GLFWvidmode*`.
- Add `CursorMode` enum that contains: `CURSOR_DISABLED`, `CURSOR_HIDDEN`, `CURSOR_NORMAL`. Supports disabling, hiding, and showing a screen cursor (mouse pointer).
- Add `WindowMode` enum that contains: `CURSOR`, `RAWMTN`. Supports cursor input and raw mouse motion input.
- Add window context management methods: `Create`, `Remove`, `Swap`, `Poll`.
- Add access methods: `GetAspectRatio`, `GetContext`, `GetCursorMode`, `GetFullscreen`, `GetPrimaryMonitor`, `GetShouldClose`, `GetSize`, `GetVideoMode`, `GetWindowMode`.
- Add mutate method: `SetCursorMode`, `SetFullscreen`, `SetShouldClose`, `SetSize`, `SetWindowMode`.
- Add GLFW window hints for bit colour depth, refresh rate, maximising, resizing, and multisampling.
- Add `BBInput` library to CMakeLists generation and linking.
- Modify `EntryPoint.cpp` to use new window class object and methods.
- Adjust resolution to 1920x1080.

### CODE REVIEW

**Review by Idraliski — CHANGES_REQUESTED** [review]
Looks great to me, Runs for me. But can we not force the construction to be in fullscreen mode please. My main monitor is 2k resolution and it has a fit when trying to resize everything (as my other monitors are not 2k). I'd imagine borderless fullscreen will have the same issues (if that was also an option)

**Comment by jdilanzo** [comment]
@Idraliski give it another run and see how it works out with the 2k monitor. Fullscreen isn't default, but I've left it maximised, so let me know if it still has a fit.

**Review by Idraliski — APPROVED** [review]
Sweet thanks for that change. also negated that odd issue in the end screen when the cube photo was off centre. Might of been when windows OS resized things

**Review by The-Spaghetti-Is-Ready — APPROVED** [review]
Looking nice, I have no issue with this

**Pull request merged**
